package com.kylin.plsql.core.format.plsql.model;

public enum PlSqlBlockType {
    PACKAGE_SPEC,
    PACKAGE_BODY,
    TYPE_SPEC,
    TYPE_BODY,
    PROCEDURE,
    FUNCTION,
    TRIGGER,
    ANON_BLOCK,
    IF,
    LOOP,
    FOR_LOOP,
    WHILE_LOOP,
    REPEAT_LOOP,
    CASE_BLOCK,
    NAMED_END,

    // DDL types
    DDL_CREATE_TABLE, DDL_CREATE_INDEX, DDL_CREATE_VIEW,
    DDL_CREATE_MVIEW, DDL_CREATE_MVIEW_LOG, DDL_CREATE_TABLESPACE,
    DDL_CREATE_USER, DDL_CREATE_ROLE, DDL_CREATE_PROFILE,
    DDL_CREATE_DIRECTORY, DDL_CREATE_SEQUENCE, DDL_CREATE_SYNONYM,
    DDL_CREATE_DATABASE_LINK, DDL_ALTER_TABLE, DDL_ALTER_INDEX,
    DDL_ALTER_TABLESPACE, DDL_ALTER_USER, DDL_ALTER_SEQUENCE,
    DDL_DROP_TABLE, DDL_DROP_INDEX, DDL_DROP_VIEW, DDL_TRUNCATE,
    DDL_RENAME, DDL_COMMENT, DDL_GRANT, DDL_REVOKE,
    DDL_FLASHBACK, DDL_PURGE, DDL_ANALYZE
}
